name: mvvm_flutter
description: The goal behind  is to move as much of the state and logic from the View into a separate entity called the BaseViewModel.
version: 0.3.0
homepage: https://github.com/SouravKumarPandit/mvvm_flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.7
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
module:
  androidX: true
#flutter:
#  plugin:
#    androidPackage: com.flutterpandit.architecture.mvvm_flutter
#    pluginClass: MvvmFlutterPlugin